### PR TITLE
Suspend the forward workflow when the reverse workflow is running #233

### LINKED ISSUE #233: Suspend the forward workflow when the reverse workflow is running
**Describe the bug**
If an ApplicationGroup is deleted in the midst of the forward workflow, the forward workflow keeps continuing while the reverse workflow tries to tear down the HelmReleases

**To Reproduce**
1. Create ApplicationGroup bookinfo
2. Delete the ApplicationGroup in the middle of the workflow

**Expected behavior**
We should suspend, pause or stop the forward workflow when the reverse workflow is generated and submitted.

**Screenshots**

**Environment (please complete the following information):**
- Kubernetes Version [e.g. 1.21.0]
- Kubernetes Distro [e.g. AKS, GKE, etc.]
- Orkestra Version Tag
- Helm Version

**Additional context**

### PR DESCRIPTION
**Pull request by davutkarabay**
This change suspends the forward workflow when the reverse workflow is running. Tested by using the bookinfo app.

### CODE REVIEW

File: controllers/appgroup_controller.go [hunk 1]
```diff
@@ -503,3 +509,21 @@ func (r *ApplicationGroupReconciler) generateReverseWorkflow(ctx context.Context
 	}
 	return nil
 }
+
+// suspend a workflow if it is not already finished or suspended
+func (r *ApplicationGroupReconciler) suspendWorkflow(ctx context.Context, logr logr.Logger, wf *v1alpha12.Workflow) error {
```
Comment (jonathan-innis) [inline controllers/appgroup_controller.go:514]: Should we also delete it? Or just suspend it?

**Review by jonathan-innis — CHANGES_REQUESTED** [review]

File: controllers/appgroup_controller.go (hunk 1 above)
Comment (jonathan-innis) [reply controllers/appgroup_controller.go:514]: Can we also add a short test case for this scenario?

Comment (nitishm) [reply controllers/appgroup_controller.go:514]: > Should we also delete it? Or just suspend it?

Deleting the forward workflow will cause all HelmReleases to be garbage collected (I think)

Comment (jonathan-innis) [reply controllers/appgroup_controller.go:514]: We don't set an ownership reference on the HelmReleases so why would this heppen?

Comment (nitishm) [reply controllers/appgroup_controller.go:514]: I have noticed when we force delete an application group (by removing the finalizer) all associated HelmReleases are cleaned up. Is that not the case?

Comment (nitishm) [reply controllers/appgroup_controller.go:514]: BTW we are adding the FW workflow as an owner of the Reverse WF
```go
			// Add OwnershipReference
			err = controllerutil.SetControllerReference(wf, a.rwf, a.scheme)
			if err != nil {
				l.Error(err, "unable to set forward workflow as owner of Argo reverse Workflow object")
				return fmt.Errorf("unable to set forward workflow as owner of Argo reverse Workflow: %w", err)
			}
```

Comment (nitishm) [reply controllers/appgroup_controller.go:514]: > We don't set an ownership reference on the HelmReleases so why would this happen?
You're right this doesn't happen. I suppose it would be ok to delete the FW workflow provided we remove the Forward workflow as the owner of the reverse WF

**Review by nitishm — CHANGES_REQUESTED** [review]
Let's get the test added and we should be set to merge this in!

File: controllers/appgroup_controller.go (hunk 1 above)
Comment (davutkarabay) [reply controllers/appgroup_controller.go:514]: Added a test case for suspend

**Comment by nitishm** [comment]
Why is the CI failing even though the test run is green? 😕

**Comment by jonathan-innis** [comment]
> Why is the CI failing even though the test run is green? 😕

Accidentally focussed a test 🤦

**Review by jonathan-innis — APPROVED** [review]
🚀 LGTM

**Comment by nitishm** [comment]
MVP complete 🎉🎉🎉🚀🚀🚀
