### PR TITLE
Update ConvertToDNS1123() to validate and fix other special characters, max len and starts-with rules

### LINKED ISSUE #252: ConvertToDNS1123 helper function should also validate and fix other special characters, max len and starts-with rules that are not compatible
Instead of just replacing `_` with `-` that we do in the function we should do something akin to https://gitlab.com/gitlab-org/gitlab-runner/-/blob/0e2ae0001684f681ff901baa85e0d63ec7838568/executors/kubernetes/util.go#L268
However, rather than replacing all violating chars with `""` as in done in the above snippet, we always replace them with `-`

### PR DESCRIPTION
**Pull request by mahalrs**
Closes #252

Now `ConvertToDNS1123()` will:
- replace all violating chars with "-"
- replace all violating start chars with ""
- in case if input or resulting name is empty string, return the hash of original input truncated to 63 chars.
- truncate right side if length > 63

### CODE REVIEW

File: pkg/utils/helpers.go [hunk 1]
```diff
@@ -4,15 +4,30 @@ import (
...
+
 func ConvertToDNS1123(in string) string {
-	return strings.ReplaceAll(in, "_", "-")
+	in = strings.ToLower(in)
+
+	notAllowedChars := regexp.MustCompile(DNS1123NotAllowedChars)
+	in = notAllowedChars.ReplaceAllString(in, "-")
+
+	notAllowedStartChars := regexp.MustCompile(DNS1123NotAllowedStartChars)
+	in = notAllowedStartChars.ReplaceAllString(in, "a")
```
Comment (nitishm) [inline pkg/utils/helpers.go:28]: can we replace it with an empty string `""`?

**Review by nitishm — DISMISSED** [review]
LGTM 🚀 !! Maybe consider the suggestion below since the `a` might be less intuitive to the end user

File: pkg/utils/helpers.go (hunk 1 above)
Comment (mahalrs) [reply pkg/utils/helpers.go:28]: Is empty string a valid name? For example, if name="?%$@!&" (all invalid chars) then first all chars will be replaced with "-" and then all "-" chars are replaced with "" because "-" is an invalid start char.

So, if we want to change "a" to "" then we can add some valid char in case of empty string.

Comment (nitishm) [reply pkg/utils/helpers.go:28]: I see your point.
Another corner case that comes up is If we have two subcharts with names `%@$!` & `##@#` and `a` how would we differentiate between each of these? Might need a cleaner way with some unique identifier than just replacing with a char. A UUID based on the input name?

Comment (nitishm) [reply pkg/utils/helpers.go:28]: Maybe the truncated hash could be an option?

Comment (nitishm) [reply pkg/utils/helpers.go:28]: If after replace output string is empty then take hash of input string and truncate to 63 chars?

Comment (mahalrs) [reply pkg/utils/helpers.go:28]: > A UUID based on the input name?

Hash of the original input name will be great.

Comment (nitishm) [reply pkg/utils/helpers.go:28]: > > A UUID based on the input name?
> 
> Hash of the original input name will be great.

Let's try that !

File: pkg/utils/chart.go [hunk 2]
```diff
@@ -1,14 +1,10 @@
...
-	//
-	// The max name length limit enforced by DNS1123 is 63 chars. We reserve 10 chars
-	// for concatenating application name hash.
-	subchartNameMaxLen = 53
-)
+// subchartNameMaxLen is the maximum length of a subchart name.
+//
+// The max name length limit enforced by DNS1123 is 63 chars. We reserve 10 chars
+// for concatenating application name hash.
+const subchartNameMaxLen = 53
```
Comment (jonathan-innis) [inline pkg/utils/chart.go:7]: Move to consts

File: pkg/utils/helpers.go [hunk 3]
```diff
@@ -4,15 +4,33 @@ import (
...
 	"fmt"
+	"regexp"
 	"strings"
 
 	fluxhelmv2beta1 "github.com/fluxcd/helm-controller/api/v2beta1"
 	"helm.sh/helm/v3/pkg/chart"
 	"sigs.k8s.io/yaml"
 )
 
+const (
```
Comment (jonathan-innis) [inline pkg/utils/helpers.go:15]: Move to `consts.go`

**Review by jonathan-innis — CHANGES_REQUESTED** [review]

**Comment by mahalrs** [comment]
@jonathan-innis Can you re-run e2e on this one too.

**Comment by nitishm** [comment]
@jonathan-innis Can we get this approved and merged in if @mahalrs has addressed your comments?

**Review by jonathan-innis — APPROVED** [review]
🚀

**Comment by mahalrs** [comment]
@jonathan-innis Can you re-run e2e workflow on this.

**Comment by nitishm** [comment]
Great stuff @mahalrs 🚀 !!
