### PR TITLE
Nitishm/bug/124/125/bug fixes

### LINKED ISSUE #124: Orkestra should copy over all non yaml resources from the parent chart into the staged subcharts
Subcharts may rely on templates and other files defined in the parent chart. Since orkestra deploys subcharts prior to the parent chart, the subchart may fail or be misconfigured if the templates are not found. To avoid this we must copy over all non-yaml files from the parent chart's template directory into the templates dir of the subcharts.

### LINKED ISSUE #125: Controller doesnt remediate on chart pull errors
Seeing the following error,
```terminal
orkestra-6bb77cb6f7-kbc8v orkestra 2021-03-25T17:28:26.880Z     ERROR   controller-runtime.controller   Reconciler error        {"controller": "applicationgroup", "request": "/bookinfo", "error": "failed to reconcile the applications : failed to pull application chart datawire/ambass:6.6.0 : failed to pull chart from repoKey datawire Name ambass Version 6.6.0 in registries map : failed to fetch https://www.getambassador.io/helm/ambass-6.6.0.tgz : 403 Forbidden"}
```
. The error is being logged but a rollback (remediation) is not taking place.

To reproduce:

1. deploy book info example till it succeeds
2. edit the applicationgroup and change the chart repo source to an invalid value (for instance switch ambassador to ambass).

### PR DESCRIPTION
**Pull request by nitishm**
fixes #124 
fixes #125

### CODE REVIEW

File: controllers/appgroup_reconciler.go [hunk 1]
```diff
@@ -98,48 +99,64 @@ func (r *ApplicationGroupReconciler) reconcileApplications(l logr.Logger, appGro
 
 			stagingRepoName := r.StagingRepoName
 			// If Dependencies - extract subchart and push each to staging registry
-			if isDependenciesEmbedded(appCh) {
-				for _, sc := range appCh.Dependencies() {
-					cs := orkestrav1alpha1.ChartStatus{
-						Version: sc.Metadata.Version,
-					}
+			// if isDependenciesEmbedded(appCh) {
```
Comment (nitishm) [inline controllers/appgroup_reconciler.go:102]: Let's do this for all subcharts (remote or embedded)
